### ISSUE TITLE
Obico-Cuda failing to start after update

### ISSUE THREAD

**Issue by TheBennyJ** [imagegenius/docker-obico#27]
Looks like something stopped working with the Cuda after the latest release (ghcr.io/imagegenius/obico:cuda). I updated my nvidia driver after to see if that helped, but no change. 

`2024-12-11 10:42:55.884207396 [E:onnxruntime:Default, provider_bridge_ort.cc:1862 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1539 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.9: cannot open shared object file: No such file or directory
2024-12-11 10:42:55.884231378 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:993 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Require cuDNN 9.* and CUDA 12.*. Please install all dependencies as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
Connection to 127.0.0.1 3333 port [tcp/*] succeeded!
[ig-init] done.`
[Obico_error.log](https://github.com/user-attachments/files/18099389/Obico_error.log)

**Comment by TheBennyJ** [comment]
I confirmed rolling back to cuda-471c0364-ig5 fixed my issue

**Comment by hydazz** [comment]
I'll have a look when i get a sec at a fix

**Comment by ados8** [comment]
I'm getting this and I'm not even on the Cuda image

**Comment by pieman3000** [comment]
Also having this issue.

2025-01-31 17:18:42.997356901 [E:onnxruntime:Default, provider_bridge_ort.cc:1862 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1539 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.9: cannot open shared object file: No such file or directory
Post-processed 'rest_framework/js/bootstrap.min.2f34b630ffe3.js' as 'rest_framework/js/bootstrap.min.2f34b630ffe3.js.br'

2025-01-31 17:18:42.997376058 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:993 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Require cuDNN 9.* and CUDA 12.*. Please install all dependencies as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
